[build]
  command = "npm run build"
  publish = ".next/standalone"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NODE_VERSION = "18"

[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 3000

# Handle Next.js routing
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Ensure all routes are handled by Next.js
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[[redirects]]
  from = "/_next/*"
  to = "/_next/:splat"
  status = 200

[[redirects]]
  from = "/static/*"
  to = "/static/:splat"
  status = 200
