[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"

[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 3000

# Handle Next.js routing
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Ensure all routes are handled by Next.js
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/nextjs-server"
  status = 200
  force = true
